services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: php-dev-base
    volumes:
      - .:/app
      - ~/.composer:/.composer
    user: 1000:1000
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      APP_DEBUG: true
    command: ./bin/server